name: Build and Deploy Documentation

on:
  push:
    branches: [main, master]
    tags: ["*"]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "Setting version to $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install dependencies
        run: uv sync --locked --all-groups

      - name: Build documentation
        run: |
          cd docs
          uv run make clean html
        env:
          VERSION: ${{ env.VERSION }}

      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          path: docs/_build/html

      - name: Upload build artifacts for debugging
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: docs-build-artifacts
          path: |
            docs/_build/
            docs/*.log

  check-main-branch:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      on-main: ${{ steps.check.outputs.on-main }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if tag is on main branch
        id: check
        run: |
          git fetch origin main
          if git merge-base --is-ancestor HEAD origin/main; then
            echo "Tag is on main branch"
            echo "on-main=true" >> $GITHUB_OUTPUT
          else
            echo "Tag is NOT on main branch"
            echo "on-main=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build, check-main-branch]
    if: startsWith(github.ref, 'refs/tags/') && needs.check-main-branch.outputs.on-main == 'true'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
